### ISSUE TITLE
Purpose of this particular line ?

### ISSUE THREAD

**Issue by philanz** [jonsamwell/angular-simple-shopping-cart#1]
https://github.com/jonsamwell/angular-simple-shopping-cart/blob/251a3923edc2a64f4899f15b6c8607903a7739e7/src/app/services/shopping-cart.service.ts#L33

**Comment by jonsamwell** [comment]
Sorry for the late reply.  That line is so that if the subscriber cancels or un-subscribes from the subscription they are removed from the list of subscribers that get notified of changes.
